events{}

http {
    server {
        listen 80;
        server_name localhost;
        location / {
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
            # en-têtes pour les websockets - à garder ?
            # proxy_set_header Upgrade $http_upgrade;
            # proxy_set_header Connection "Upgrade";
        }
    }
    # server {
    #     listen 80;
    #     server_name backoffice.localhost;
    #     location / {
    #         proxy_pass http://backoffice:5174;
    #         proxy_set_header Host $host;
    #         # en-têtes pour les websockets - à garder ?
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection "Upgrade";
    #     }
    # }
    server {
        listen 80;
        server_name backend.localhost;
        location / {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
        }
    }
}